### ISSUE TITLE
小组赛之后就不能显示了嘛

### ISSUE THREAD

**Issue by shenyouwuwai** [lisongqian/Scriptable#1]

**Comment by lisongqian** [comment]
问题在1.1.0版本中修复，重新运行小组件即可。

**Comment by shenyouwuwai** [comment]
能再更新一么？让这个小组件走到决赛吧。
如果可以的话，让这个小组件下个世界杯还接着复用。

**Comment by lisongqian** [comment]
> 能再更新一么？让这个小组件走到决赛吧。 如果可以的话，让这个小组件下个世界杯还接着复用。

问题已解决。关于下一届世界杯是否可用的问题，到2026年fifa官方是否会改变api是未知的。若保持不变，小组件可继续支持。

**Comment by shenyouwuwai** [comment]
辛苦了，谢谢。
